#!/bin/bash
# Switch between BitNet models easily
#
# Usage: ./switch-model.sh [model]
#
# Models:
#   2b      - BitNet-b1.58-2B-4T (fast, basic tool use)
#   large   - bitnet_b1_58-large 0.7B (fastest, limited)
#   3b      - bitnet_b1_58-3B (balanced)
#   8b      - Llama3-8B-1.58-100B-tokens (best tool use)

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$SCRIPT_DIR/../.env"

MODEL=${1:-""}

# Show current model if no argument
if [ -z "$MODEL" ]; then
    echo "Current model configuration:"
    if [ -f "$ENV_FILE" ]; then
        grep "BITNET_MODEL" "$ENV_FILE" || echo "  (using default)"
    else
        echo "  (using default: BitNet-b1.58-2B-4T)"
    fi
    echo ""
    echo "Usage: ./switch-model.sh [model]"
    echo ""
    echo "Available models:"
    echo "  2b     - BitNet-b1.58-2B-4T     ~4GB RAM  (default, fast)"
    echo "  large  - bitnet_b1_58-large     ~2GB RAM  (fastest, limited)"
    echo "  3b     - bitnet_b1_58-3B        ~6GB RAM  (balanced)"
    echo "  8b     - Llama3-8B-1.58-bit     ~12GB RAM (best for tools)"
    echo ""
    echo "Example: ./switch-model.sh 8b"
    exit 0
fi

case $MODEL in
    2b|2B|default)
        MODEL_PATH="/models/BitNet-b1.58-2B-4T/ggml-model-i2_s.gguf"
        MODEL_NAME="BitNet-b1.58-2B-4T (2B)"
        THREADS=4
        CTX=4096
        MEM="8G"
        ;;
    large|0.7b|small|fast)
        MODEL_PATH="/models/bitnet_b1_58-large/ggml-model-i2_s.gguf"
        MODEL_NAME="bitnet_b1_58-large (0.7B)"
        THREADS=2
        CTX=2048
        MEM="4G"
        ;;
    3b|3B|balanced)
        MODEL_PATH="/models/bitnet_b1_58-3B/ggml-model-i2_s.gguf"
        MODEL_NAME="bitnet_b1_58-3B (3.3B)"
        THREADS=4
        CTX=4096
        MEM="10G"
        ;;
    8b|8B|llama3|best|tools)
        MODEL_PATH="/models/Llama3-8B-1.58-100B-tokens/ggml-model-i2_s.gguf"
        MODEL_NAME="Llama3-8B-1.58-100B-tokens (8B)"
        THREADS=6
        CTX=8192
        MEM="16G"
        ;;
    *)
        echo "Unknown model: $MODEL"
        echo "Run without arguments to see available models."
        exit 1
        ;;
esac

echo "Switching to: $MODEL_NAME"
echo ""

# Create/update .env file
cat > "$ENV_FILE" << EOF
# BitNet Model Configuration
# Generated by switch-model.sh on $(date)

BITNET_MODEL=$MODEL_PATH
BITNET_THREADS=$THREADS
BITNET_CTX_SIZE=$CTX

# Docker resource limits
BITNET_MEMORY_LIMIT=$MEM
EOF

echo "Configuration saved to .env"
echo ""
echo "  Model:    $MODEL_PATH"
echo "  Threads:  $THREADS"
echo "  Context:  $CTX"
echo "  Memory:   $MEM"
echo ""

# Check if services are running
if docker compose ps --status running 2>/dev/null | grep -q "bitnet"; then
    echo "Services are running. Restart to apply changes:"
    echo "  docker compose down && docker compose up -d"
else
    echo "Start services with:"
    echo "  docker compose up -d"
fi
